node {
	def repository_id = "bigdata-releases"
	def group_id = "net.zylklab.bigdata"
	def group_id_path = "net/zylklab/bigdata"
	def artifact_id = "grafana-kafka-rest"
	def artifact_type = "war"
	def nexus_url = "https://services.zylk.net/nexus"
	def rest_repository_url = "${nexus_url}/content/repositories/${repository_id}"
	def nexus_read_credentials = "nexus-read-user"
	
	def host_name = sh (returnStdout: true, script:"hostname -f").trim()
	if(host_name.endsWith("zylk.net")) {
		def versions
		withCredentials([ usernameColonPassword(credentialsId: "${nexus_read_credentials}", variable: "USERPASS")]) {
			global_USERPASS = "${USERPASS}"
			echo "curl versions"
			versions = sh(returnStdout: true, script: "curl -X GET -u '${USERPASS}' --fail -L 'https://services.zylk.net/nexus/service/local/lucene/search?repositoryId=${repository_id}&g=${group_id}&a=${artifact_id}' | sed -e '/version/ !d' | sed 's:<version>\\|</version>::g'")
			
			// long version of: versions.split().reverse().sublist(0,10).join("\n")
			versions = versions.split()
			tmp_versions = versions.clone()
			for (i = 0; i < versions.size(); i++) {
				tmp_versions[-1-i] = versions[i]
			}
			while (tmp_versions.size() > 10) {
				tmp_versions.remove(tmp_versions.size()-1)
			}
			versions = tmp_versions.join("\n")
			echo "${versions}"
		}
		properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')), disableConcurrentBuilds(),
		parameters([ string(defaultValue: 'ZYLK', description: 'Deploy Environment (ZYLK)', name: 'environment'),
						string(defaultValue: 'grafana-kafka-rest', description: 'Rest module artifact id (grafana-kafka-rest)', name: 'rest_artifact_id'),
						choice(choices: "Latest\n${versions}", description: 'Rest module Version', name: 'rest_version')]),
						pipelineTriggers([])])
	}
	
	def deploy_remote_host
	def tomcat_remote_path
	def tomcat_deploy_credentials
	def tomcat_deploy_user

	if (environment == 'ZYLK') {
		deploy_remote_host = "amaterasu004.bigdata.zylk.net"
		tomcat_remote_path = "/opt/tomcat/latest"
		tomcat_deploy_credentials="grafana-amaterasu"
		tomcat_deploy_user = "tomcat"
	}
	
	if (env.BRANCH_NAME == "master" && environment == 'ZYLK') {
		stage ('Get artifact') {
			if ("${rest_version}" == "Latest") {
				withCredentials([usernameColonPassword(credentialsId: "${nexus_read_credentials}", variable: "USERPASS")]) {
					echo "curl latest version"
					rest_version = sh(returnStdout: true, script: "curl -X GET -u '${USERPASS}' --fail -L 'https://services.zylk.net/nexus/service/local/lucene/search?repositoryId=${repository_id}&g=${group_id}&a=${artifact_id}' | sed -e '/latestRelease/ !d' | head -1 | sed 's:<latestRelease>\\|</latestRelease>::g'").trim()
					echo "latest version: ${rest_version}"
				}
			}
			withCredentials([usernameColonPassword(credentialsId: "${nexus_read_credentials}", variable: "USERPASS")]) {
				echo "curl --fail -L ${rest_repository_url}/${group_id_path}/${rest_artifact_id}/${rest_version}/${rest_artifact_id}-${rest_version}.${artifact_type}"
				sh "curl -u '${USERPASS}' --fail -L '${rest_repository_url}/${group_id_path}/${rest_artifact_id}/${rest_version}/${rest_artifact_id}-${rest_version}.${artifact_type}' -o ${rest_artifact_id}-${rest_version}.${artifact_type}"
			}
		}
		stage ('Move artifact to deploy zone') {
			sshagent (credentials: ["${tomcat_deploy_credentials}"]) {
				echo "copy artifact ./${rest_artifact_id}-${rest_version}.${artifact_type} to ${tomcat_deploy_user}@${deploy_remote_host}:${tomcat_remote_path}/webapps/${rest_artifact_id}.${artifact_type}"
				sh "scp -o StrictHostKeyChecking=no ./${rest_artifact_id}-${rest_version}.${artifact_type} ${tomcat_deploy_user}@${deploy_remote_host}:${tomcat_remote_path}/webapps/${rest_artifact_id}.${artifact_type}"
			}
		}
		
		stage ('Restart the container (thread force)') {
			sshagent (credentials: ["${tomcat_deploy_credentials}"]) {
				echo "restarting tomcat.service at ${deploy_remote_host}"
				sh "ssh ${tomcat_deploy_user}@${deploy_remote_host} sudo systemctl restart tomcat.service"
			}
		}
	}
}